### ISSUE TITLE
plugin lavori pubblici cannot save

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2-C040#210]
### Description
the lavori pubblici plugin shows an error when trying to save.
![image](https://user-images.githubusercontent.com/11991428/60897304-230f1400-a268-11e9-855b-1133a715606e.png)

### Depends On (optional)
 - A list of other involved issues (with link)
 - ...

### Please indicate if this issue is related to a bug or a new feature request
- [x] Bug
- [ ] New Feature

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- following the steps of this [hiptest](https://app.hiptest.com/projects/47740/test-runs/278182/folder-snapshots/2503284/scenario-snapshots/9494562/test-snapshots/12218159)

*Expected Result*

- to be able to save and to see some elements on loading (yellow polygons)

*Current Result*

- no elements are selected and cannot save

### Other useful information (optional):

error of the failing request
```
<?xml version="1.0" encoding="UTF-8"?><ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/ows http://vm-linuxgeofetest.comune.genova.it:80/geoserver-test/schemas/ows/1.0.0/owsExceptionReport.xsd?ms2-authkey=247cf93a-d791-4277-a63e-46210b2b0928">
  <ows:Exception exceptionCode="InvalidParameterValue">
    <ows:ExceptionText>Error performing insert: Error inserting features</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
```

requests that fail to save
```
curl 'http://vm-linuxgeofetest.comune.genova.it/geoserver-test/ows?service=WFS&version=1.1.0&ms2-authkey=247cf93a-d791-4277-a63e-46210b2b0928' -H 'Origin: http://vm-linuxgeofetest.comune.genova.it' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36' -H 'Content-Type: application/xml' -H 'Accept: application/json, text/plain, */*' -H 'Referer: http://vm-linuxgeofetest.comune.genova.it/MapStore2/lavoriPubblici.html' -H 'Cookie: JSESSIONID=1FCBD20AF8536133B599513EE355F280; GS_FLOW_CONTROL="GS_CFLOW_-473ba5b5:16bd5f71238:7eba"' -H 'Connection: keep-alive' --data-binary '<wfs:Transaction service="WFS" version="1.1.0" xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs" xmlns:CORSO_1="http://sit.comune.genova.it/CORSO_1"><wfs:Delete typeName="CORSO_1:AREE_CANTIERE"><ogc:Filter><ogc:And><ogc:PropertyIsEqualTo><ogc:PropertyName>ID_CANTIERE</ogc:PropertyName><ogc:Literal>016799::1::1</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>TIPOLOGIA</ogc:PropertyName><ogc:Literal>cantiere</ogc:Literal></ogc:PropertyIsEqualTo></ogc:And></ogc:Filter></wfs:Delete><wfs:Insert><CORSO_1:AREE_CANTIERE><CORSO_1:ID_ELEMENTO>1388</CORSO_1:ID_ELEMENTO><CORSO_1:ID_CANTIERE>016799::1::1</CORSO_1:ID_CANTIERE><CORSO_1:TIPOLOGIA>cantiere</CORSO_1:TIPOLOGIA><CORSO_1:GEOMETRY><gml:MultiPolygon srsName="EPSG:4326"><gml:polygonMember><gml:Polygon srsName="EPSG:4326"><gml:exterior><gml:LinearRing><gml:posList>8.96748874 44.404048259999996 8.97014949 44.40303648 8.97199485 44.40288318000001 8.97053573 44.40506002 8.96748874 44.404048259999996</gml:posList></gml:LinearRing></gml:exterior></gml:Polygon></gml:polygonMember></gml:MultiPolygon></CORSO_1:GEOMETRY></CORSO_1:AREE_CANTIERE></wfs:Insert></wfs:Transaction>' --compressed --insecure
```

this is the error in geoserver
```
Caused by: java.io.IOException: Error inserting features
	at org.geotools.jdbc.JDBCDataStore.insert(JDBCDataStore.java:1794)
	at org.geotools.jdbc.JDBCInsertFeatureWriter.flush(JDBCInsertFeatureWriter.java:128)
	at org.geotools.jdbc.JDBCInsertFeatureWriter.write(JDBCInsertFeatureWriter.java:100)
	at org.geotools.data.InProcessLockingManager$1.write(InProcessLockingManager.java:304)
	at org.geotools.data.store.ContentFeatureStore.addFeature(ContentFeatureStore.java:311)
	at org.geotools.data.store.ContentFeatureStore.addFeatures(ContentFeatureStore.java:258)
	at org.vfny.geoserver.global.GeoServerFeatureStore.addFeatures(GeoServerFeatureStore.java:80)
	at org.geoserver.security.decorators.SecuredFeatureStore.addFeatures(SecuredFeatureStore.java:65)
	at org.geoserver.wfs.InsertElementHandler.execute(InsertElementHandler.java:191)
	... 123 more
Caused by: java.sql.BatchUpdateException: ORA-01031: insufficient privileges

	at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:12296)
	at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:246)
	at org.apache.tomcat.dbcp.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297)
	at org.apache.tomcat.dbcp.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297)
	at org.apache.tomcat.dbcp.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297)
	at org.geotools.jdbc.JDBCDataStore.insertPS(JDBCDataStore.java:1861)
	at org.geotools.jdbc.JDBCDataStore.insert(JDBCDataStore.java:1780)
	... 131 more
```

schema is different from the two geoserver
in test is ORSO_1
in prod is CANTIERI

**Comment by MV88** [comment]
Note: Check on geoserver log and check if the layer is writable
