### ISSUE TITLE
MapStore Update

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#445]
### Description
The MapStore revision need to be updated to the latest stable branch 2021.0?.xx.

The MapStore currently installed is enough recent. It is anyway necessary to check if the existing customizations are properly working after the project update. Custom or client's specific extensions are the following **that will be checked during the PR review**:

- [x] **Thematic Maps / Statistical Query Engine Update**: Not officially maintained. It is necessary to check it after the update (a reference map [here](https://mappe.comune.genova.it/MapStore2/#/viewer/openlayers/1000002291) in production environment). Hiptest available [here](https://studio.cucumber.io/projects/47740/test-runs/421040/folder-snapshots/4008457/scenario-snapshots/14592539/test-snapshots/19053266).

- [x] **Integration with SPID** (italian authentication system for Public Administrations): to check after the update. Hiptest available [here](https://studio.cucumber.io/projects/47740/test-runs/421040/folder-snapshots/4008465/scenario-snapshots/14592553/test-snapshots/19053280).

- [x] **GeoCollect embedded**: to check after the update. Hiptests are available [here](https://studio.cucumber.io/projects/47740/test-runs/421040/folder-snapshots/4008459/scenario-snapshots/14592543/test-snapshots/19053270) and [here](https://studio.cucumber.io/projects/47740/test-runs/421040/folder-snapshots/4008464/scenario-snapshots/14592549/test-snapshots/19053276)

- [x] **FeatureViewer**: to check after the update. Hiptest available [here](https://studio.cucumber.io/projects/47740/test-runs/421040/folder-snapshots/4008466/scenario-snapshots/14592554/test-snapshots/19053281)

- [x] **Public Works Plugin**: to check after the update. Hiptest is available [here](https://studio.cucumber.io/projects/47740/test-runs/421040/folder-snapshots/4008466/scenario-snapshots/14592555/test-snapshots/19053282)

### Other useful information:
The master branch of the project will be updated first, then the production one will be accordingly updated before moving things in production environment.

**Comment by tdipisa** [comment]
@offtherailz please use 2021.01.xx

**Comment by ElenaGallo** [comment]
@offtherailz @tdipisa the  **GeoCollect** has some problem, running the GFI displays the infinite loading spinner.

**How to Reproduce**
Follow the steps below or the hiptest [here](https://studio.cucumber.io/projects/47740/test-runs/566300/folder-snapshots/5667888/scenario-snapshots/20116395/test-snapshots/27257578):
![geoCollect1](https://user-images.githubusercontent.com/56537133/126616006-060a67b3-fa78-4f46-a280-bebbc467d04f.gif)


### Other useful information:
The same problem is present on the mbedded GeoCollect map, an example [here](https://github.com/geosolutions-it/MapStore2-C040/files/6861164/ge.zip)

**Comment by offtherailz** [comment]
@tdipisa Is geocollect supported yet? 
I remember it was not. If so, we should remove the related tests

**Comment by tdipisa** [comment]
@offtherailz yes, it is still needed. Last time the client asked this even if it is less used now.

**Comment by MV88** [comment]
@tdipisa @offtherailz 
the geocollect has two problems 
- [ DEV only ] the spinner never goes away because no valid responses are returned
- [ DEV and PROD ] when clink on the map the GFI request passes through the proxy and it returns nothing, instead when done directly it returns correctly the features

request through proxy
https://mappe.comune.genova.it/MapStore2/proxy/?url=https%3A%2F%2Fgeocollect.geo-solutions.it%2Fgeoserver%2Fit.geosolutions%2Fows%3Fservice%3DWMS%26version%3D1.1.1%26request%3DGetFeatureInfo%26exceptions%3Dapplication%252Fjson%26id%3Dcens_muri__8%26layers%3Dcens_muri%26query_layers%3Dcens_muri%26x%3D51%26y%3D51%26height%3D101%26width%3D101%26srs%3DEPSG%253A3857%26bbox%3D1025593.8270163524%252C5542831.106099555%252C1033313.9668731552%252C5550551.245956358%26feature_count%3D10%26info_format%3Dapplication%252Fjson%26ENV%3D

direct request
https://geocollect.geo-solutions.it/geoserver/it.geosolutions/ows?service=WMS&version=1.1.1&request=GetFeatureInfo&exceptions=application%2Fjson&id=cens_muri__8&layers=cens_muri&query_layers=cens_muri&x=51&y=51&height=101&width=101&srs=EPSG%3A3857&bbox=1025593.8270163524%2C5542831.106099555%2C1033313.9668731552%2C5550551.245956358&feature_count=10&info_format=application%2Fjson&ENV=

**Comment by tdipisa** [comment]
@MV88

As you noticed the problem is that MS receives an empty response. The fact that the loading spinner doesn't disappear in this situation is due to a regression in MS that must be fixed, so please proceed with that as we agreed by also backporting to 2021.01.xx

For what concern the empty response, this is due to the fact that the request is performed through the MS proxy and this error is reported in the tomcat log:

```
Aug 24, 2021 11:49:08 AM it.geosolutions.httpproxy.HTTPProxy executeProxyRequest
SEVERE: Error executing HTTP method
javax.net.ssl.SSLHandshakeException: received handshake warning: unrecognized_name
        at sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:311)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
        at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:272)
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1383)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1291)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:435)
        at sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:804)
        at sun.security.ssl.SSLSocketImpl.access$200(SSLSocketImpl.java:73)
        at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1166)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:828)
        at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.flushRequestOutputStream(MultiThreadedHttpConnectionManager.java:1565)
        at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2116)
        at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at it.geosolutions.httpproxy.HTTPProxy.executeProxyRequest(HTTPProxy.java:692)
        at it.geosolutions.httpproxy.HTTPProxy.doGet(HTTPProxy.java:295)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
```

Checking online I found that this is an exception occurring since Java 1.7 when trying to establish a connection to the webserver over SSL (see [here](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=7127374)).

For the moment I've applied a workaround by including the additional java_opt as required:

`-Djsse.enableSNIExtension=false`

But I think it would be better to provide a definitive fix server side by reviewing the server configuration at **geocollect.geo-solutions.it**

**Comment by lpasquali** [comment]
@tdipisa I think that the workaround is the only IT side solution and it might be to be fixed pragmatically https://stackoverflow.com/questions/55903477/received-handshake-warning-unrecognized-name

**Comment by tdipisa** [comment]
@lpasquali as we discussed, this is a problem that involves only ajaxs requests to the geocollect geoserver (gs-stable is not involved for example) probably due to the different https certificate or something else.
In addition, the geosolutions geocollect geoserver is not so used and it will be probably decommissioned in the future. 

For the above reasons the solution using the _jsse.enableSNIExtension_ optionis acceptable for now since it doesn't not introduce collateral issues.

@ElenaGallo please test again the issue and update the hiptest for genova accordingly.
