### ISSUE TITLE
Print fails because of wrong scale sent

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2-C040#541]
## Description

the scale calculated and sent as print spec is wrong 
![image](https://user-images.githubusercontent.com/11991428/159059654-f77f446c-fa3a-4162-9718-b577c5c72b3d.png)
Before it was sending 5000 as scale taken from spec.scale

## How to reproduce

- open a map with this project aligned to 2022.01.xx (currently [here](https://github.com/MV88/MapStore2-C040/tree/538_update_2022.01.xx)) 
- try to print something

*Expected Result*

to print

*Current Result*

```
in genova sto avendo questo problema con il print
Error while generating PDF:
org.mapfish.print.InvalidJsonValueException: spec.pages[0].scale has an invalid value: 9244667
	at org.mapfish.print.config.layout.MapBlock.createTransformer(MapBlock.java:140)
	at org.mapfish.print.config.layout.MapBlock.render(MapBlock.java:57)
	at org.mapfish.print.config.layout.Page.render(Page.java:80)
	at org.mapfish.print.config.layout.Layout.render(Layout.java:67)
	at org.mapfish.print.output.AbstractOutputFormat.doPrint(AbstractOutputFormat.java:30)
	at org.mapfish.print.output.PdfOutputFactory.print(PdfOutputFactory.java:62)
```

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

this is blocking

Related to https://github.com/geosolutions-it/MapStore2/issues/8000

**Comment by tdipisa** [comment]
@offtherailz should we take this in a different way with latest printing updates provided in 2022.01.00?
